"""
CIFAKE Downloader
=================

CIFAKE is a peer-reviewed dataset (Bird & Lotfi, 2023):
  - 60,000 real images sourced from CIFAR-10 (real photographs)
  - 60,000 AI images generated by Stable Diffusion v1.4

Label mapping (verified by inspecting dataset features):
  0 = FAKE (AI generated)
  1 = REAL (photograph)

Known limitation: images are 32×32 pixels — low resolution.
At this scale, some natural texture differences between real and AI
are lost, which contributes to the confident mistakes we observed.
This is why we supplement CIFAKE with higher-resolution sources.
"""

from pathlib import Path


def download(source: dict, output_dir: Path):
    try:
        from datasets import load_dataset
    except ImportError:
        raise ImportError("Run: pip install datasets")

    ai_dir   = output_dir / "ai_generated"
    real_dir = output_dir / "real"
    ai_dir.mkdir(parents=True, exist_ok=True)
    real_dir.mkdir(parents=True, exist_ok=True)

    samples = source["samples"]
    print(f"  Streaming {source['hf_dataset']} (up to {samples} per class)...")

    ds = load_dataset(source["hf_dataset"], streaming=True)
    split = ds.get(source["split"], ds.get("train", ds.get("all")))
    if split is None:
        raise ValueError(f"Could not find split '{source['split']}' in {source['hf_dataset']}")

    real_count = ai_count = 0

    for example in split:
        if real_count >= samples and ai_count >= samples:
            break

        label = example.get(source["label_key"])
        img   = example.get(source["image_key"])
        if img is None or label is None:
            continue

        if label == source["real_label"] and real_count < samples:
            img.save(real_dir / f"real_{real_count:05d}.jpg")
            real_count += 1
        elif label == source["ai_label"] and ai_count < samples:
            img.save(ai_dir / f"ai_{ai_count:05d}.jpg")
            ai_count += 1

        if (real_count + ai_count) % 500 == 0 and (real_count + ai_count) > 0:
            print(f"    {real_count} real, {ai_count} AI...", end="\r")

    print(f"    Done: {real_count} real, {ai_count} AI saved to {output_dir}")
    return real_count, ai_count
